### PR TITLE
Follow Redirects when requesting calendars

### PR DESCRIPTION
**Pull request by varon**
- Add follow-redirects v1.15.2 package
- Follow redirects when requesting calendar links

This solves some problems that arise when following calendar links that are redirections, which can be possible under some highly dynamic situations with generated calendars.

### CODE REVIEW

**Comment by uamanager** [comment]
Hey, thank you for your PR.
Do you have issues with redirects while fetching calendar?
Or/and do you know public calendar provider which uses redirects before returning calendar?

I wish not to add more packages or code that can be redundant.

**Comment by varon** [comment]
Thank you for getting back to me on this.

Yes, I had very specific issues with pulling Calendars from GitHub directly - this is what lead me to implementing this. I'm running that on my setup and it solves the problem completely. 

I can email you the calendar link privately if you message me at varon-github@outlook.com.

**Comment by varon** [comment]
To clarify, without this in place, the plugin cannot download calendars from Github releases.

**Comment by uamanager** [comment]
Looks like something that should definitely be a part of lib.

Thank you for your interest and fixes!

**Comment by uamanager** [comment]
Latest version is released with your changes!
Thank you for your effort!

Stay safe 🇺🇦

**Comment by varon** [comment]
Thank you very much. I appreciate your help in getting these merged.

**Pull request merged**
